//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Combis_assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podaci
    {
        public int id { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string postanski_broj { get; set; }
        public string grad { get; set; }
        public string telefon { get; set; }
    }
}
